// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sdk.proto

package pbuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response_Status int32

const (
	Response_OK    Response_Status = 0
	Response_ERROR Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var Response_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}

func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{18, 0}
}

type GameLiftResponse_Status int32

const (
	GameLiftResponse_OK        GameLiftResponse_Status = 0
	GameLiftResponse_ERROR_400 GameLiftResponse_Status = 1
	GameLiftResponse_ERROR_500 GameLiftResponse_Status = 2
)

var GameLiftResponse_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR_400",
	2: "ERROR_500",
}

var GameLiftResponse_Status_value = map[string]int32{
	"OK":        0,
	"ERROR_400": 1,
	"ERROR_500": 2,
}

func (x GameLiftResponse_Status) String() string {
	return proto.EnumName(GameLiftResponse_Status_name, int32(x))
}

func (GameLiftResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{19, 0}
}

//SDK --> AuxProxy
type ProcessReady struct {
	LogPathsToUpload          []string `protobuf:"bytes,1,rep,name=logPathsToUpload,proto3" json:"logPathsToUpload,omitempty"`
	Port                      int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	MaxConcurrentGameSessions int32    `protobuf:"varint,3,opt,name=maxConcurrentGameSessions,proto3" json:"maxConcurrentGameSessions,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *ProcessReady) Reset()         { *m = ProcessReady{} }
func (m *ProcessReady) String() string { return proto.CompactTextString(m) }
func (*ProcessReady) ProtoMessage()    {}
func (*ProcessReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{0}
}

func (m *ProcessReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessReady.Unmarshal(m, b)
}
func (m *ProcessReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessReady.Marshal(b, m, deterministic)
}
func (m *ProcessReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessReady.Merge(m, src)
}
func (m *ProcessReady) XXX_Size() int {
	return xxx_messageInfo_ProcessReady.Size(m)
}
func (m *ProcessReady) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessReady.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessReady proto.InternalMessageInfo

func (m *ProcessReady) GetLogPathsToUpload() []string {
	if m != nil {
		return m.LogPathsToUpload
	}
	return nil
}

func (m *ProcessReady) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ProcessReady) GetMaxConcurrentGameSessions() int32 {
	if m != nil {
		return m.MaxConcurrentGameSessions
	}
	return 0
}

type ProcessEnding struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessEnding) Reset()         { *m = ProcessEnding{} }
func (m *ProcessEnding) String() string { return proto.CompactTextString(m) }
func (*ProcessEnding) ProtoMessage()    {}
func (*ProcessEnding) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{1}
}

func (m *ProcessEnding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessEnding.Unmarshal(m, b)
}
func (m *ProcessEnding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessEnding.Marshal(b, m, deterministic)
}
func (m *ProcessEnding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessEnding.Merge(m, src)
}
func (m *ProcessEnding) XXX_Size() int {
	return xxx_messageInfo_ProcessEnding.Size(m)
}
func (m *ProcessEnding) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessEnding.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessEnding proto.InternalMessageInfo

type GameSessionActivate struct {
	GameSessionId        string   `protobuf:"bytes,1,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	MaxPlayers           int32    `protobuf:"varint,2,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameSessionActivate) Reset()         { *m = GameSessionActivate{} }
func (m *GameSessionActivate) String() string { return proto.CompactTextString(m) }
func (*GameSessionActivate) ProtoMessage()    {}
func (*GameSessionActivate) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{2}
}

func (m *GameSessionActivate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSessionActivate.Unmarshal(m, b)
}
func (m *GameSessionActivate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSessionActivate.Marshal(b, m, deterministic)
}
func (m *GameSessionActivate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSessionActivate.Merge(m, src)
}
func (m *GameSessionActivate) XXX_Size() int {
	return xxx_messageInfo_GameSessionActivate.Size(m)
}
func (m *GameSessionActivate) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSessionActivate.DiscardUnknown(m)
}

var xxx_messageInfo_GameSessionActivate proto.InternalMessageInfo

func (m *GameSessionActivate) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

func (m *GameSessionActivate) GetMaxPlayers() int32 {
	if m != nil {
		return m.MaxPlayers
	}
	return 0
}

func (m *GameSessionActivate) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GameSessionTerminate struct {
	GameSessionId        string   `protobuf:"bytes,1,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameSessionTerminate) Reset()         { *m = GameSessionTerminate{} }
func (m *GameSessionTerminate) String() string { return proto.CompactTextString(m) }
func (*GameSessionTerminate) ProtoMessage()    {}
func (*GameSessionTerminate) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{3}
}

func (m *GameSessionTerminate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSessionTerminate.Unmarshal(m, b)
}
func (m *GameSessionTerminate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSessionTerminate.Marshal(b, m, deterministic)
}
func (m *GameSessionTerminate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSessionTerminate.Merge(m, src)
}
func (m *GameSessionTerminate) XXX_Size() int {
	return xxx_messageInfo_GameSessionTerminate.Size(m)
}
func (m *GameSessionTerminate) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSessionTerminate.DiscardUnknown(m)
}

var xxx_messageInfo_GameSessionTerminate proto.InternalMessageInfo

func (m *GameSessionTerminate) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

type UpdatePlayerSessionCreationPolicy struct {
	GameSessionId                  string   `protobuf:"bytes,1,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	NewPlayerSessionCreationPolicy string   `protobuf:"bytes,2,opt,name=newPlayerSessionCreationPolicy,proto3" json:"newPlayerSessionCreationPolicy,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *UpdatePlayerSessionCreationPolicy) Reset()         { *m = UpdatePlayerSessionCreationPolicy{} }
func (m *UpdatePlayerSessionCreationPolicy) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerSessionCreationPolicy) ProtoMessage()    {}
func (*UpdatePlayerSessionCreationPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{4}
}

func (m *UpdatePlayerSessionCreationPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerSessionCreationPolicy.Unmarshal(m, b)
}
func (m *UpdatePlayerSessionCreationPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerSessionCreationPolicy.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerSessionCreationPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerSessionCreationPolicy.Merge(m, src)
}
func (m *UpdatePlayerSessionCreationPolicy) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerSessionCreationPolicy.Size(m)
}
func (m *UpdatePlayerSessionCreationPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerSessionCreationPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerSessionCreationPolicy proto.InternalMessageInfo

func (m *UpdatePlayerSessionCreationPolicy) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

func (m *UpdatePlayerSessionCreationPolicy) GetNewPlayerSessionCreationPolicy() string {
	if m != nil {
		return m.NewPlayerSessionCreationPolicy
	}
	return ""
}

type AcceptPlayerSession struct {
	GameSessionId        string   `protobuf:"bytes,1,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	PlayerSessionId      string   `protobuf:"bytes,2,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptPlayerSession) Reset()         { *m = AcceptPlayerSession{} }
func (m *AcceptPlayerSession) String() string { return proto.CompactTextString(m) }
func (*AcceptPlayerSession) ProtoMessage()    {}
func (*AcceptPlayerSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{5}
}

func (m *AcceptPlayerSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptPlayerSession.Unmarshal(m, b)
}
func (m *AcceptPlayerSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptPlayerSession.Marshal(b, m, deterministic)
}
func (m *AcceptPlayerSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptPlayerSession.Merge(m, src)
}
func (m *AcceptPlayerSession) XXX_Size() int {
	return xxx_messageInfo_AcceptPlayerSession.Size(m)
}
func (m *AcceptPlayerSession) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptPlayerSession.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptPlayerSession proto.InternalMessageInfo

func (m *AcceptPlayerSession) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

func (m *AcceptPlayerSession) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

type RemovePlayerSession struct {
	GameSessionId        string   `protobuf:"bytes,1,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	PlayerSessionId      string   `protobuf:"bytes,2,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePlayerSession) Reset()         { *m = RemovePlayerSession{} }
func (m *RemovePlayerSession) String() string { return proto.CompactTextString(m) }
func (*RemovePlayerSession) ProtoMessage()    {}
func (*RemovePlayerSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{6}
}

func (m *RemovePlayerSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePlayerSession.Unmarshal(m, b)
}
func (m *RemovePlayerSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePlayerSession.Marshal(b, m, deterministic)
}
func (m *RemovePlayerSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePlayerSession.Merge(m, src)
}
func (m *RemovePlayerSession) XXX_Size() int {
	return xxx_messageInfo_RemovePlayerSession.Size(m)
}
func (m *RemovePlayerSession) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePlayerSession.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePlayerSession proto.InternalMessageInfo

func (m *RemovePlayerSession) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

func (m *RemovePlayerSession) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

type ReportHealth struct {
	HealthStatus         bool     `protobuf:"varint,1,opt,name=healthStatus,proto3" json:"healthStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportHealth) Reset()         { *m = ReportHealth{} }
func (m *ReportHealth) String() string { return proto.CompactTextString(m) }
func (*ReportHealth) ProtoMessage()    {}
func (*ReportHealth) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{7}
}

func (m *ReportHealth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportHealth.Unmarshal(m, b)
}
func (m *ReportHealth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportHealth.Marshal(b, m, deterministic)
}
func (m *ReportHealth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportHealth.Merge(m, src)
}
func (m *ReportHealth) XXX_Size() int {
	return xxx_messageInfo_ReportHealth.Size(m)
}
func (m *ReportHealth) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportHealth.DiscardUnknown(m)
}

var xxx_messageInfo_ReportHealth proto.InternalMessageInfo

func (m *ReportHealth) GetHealthStatus() bool {
	if m != nil {
		return m.HealthStatus
	}
	return false
}

type DescribePlayerSessionsRequest struct {
	GameSessionId             string   `protobuf:"bytes,1,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	PlayerId                  string   `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerSessionId           string   `protobuf:"bytes,3,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	PlayerSessionStatusFilter string   `protobuf:"bytes,4,opt,name=playerSessionStatusFilter,proto3" json:"playerSessionStatusFilter,omitempty"`
	NextToken                 string   `protobuf:"bytes,5,opt,name=nextToken,proto3" json:"nextToken,omitempty"`
	Limit                     int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *DescribePlayerSessionsRequest) Reset()         { *m = DescribePlayerSessionsRequest{} }
func (m *DescribePlayerSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribePlayerSessionsRequest) ProtoMessage()    {}
func (*DescribePlayerSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{8}
}

func (m *DescribePlayerSessionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePlayerSessionsRequest.Unmarshal(m, b)
}
func (m *DescribePlayerSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePlayerSessionsRequest.Marshal(b, m, deterministic)
}
func (m *DescribePlayerSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePlayerSessionsRequest.Merge(m, src)
}
func (m *DescribePlayerSessionsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribePlayerSessionsRequest.Size(m)
}
func (m *DescribePlayerSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePlayerSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePlayerSessionsRequest proto.InternalMessageInfo

func (m *DescribePlayerSessionsRequest) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetPlayerSessionStatusFilter() string {
	if m != nil {
		return m.PlayerSessionStatusFilter
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type BackfillMatchmakingRequest struct {
	TicketId                    string    `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	GameSessionArn              string    `protobuf:"bytes,2,opt,name=gameSessionArn,proto3" json:"gameSessionArn,omitempty"`
	MatchmakingConfigurationArn string    `protobuf:"bytes,3,opt,name=matchmakingConfigurationArn,proto3" json:"matchmakingConfigurationArn,omitempty"`
	Players                     []*Player `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}  `json:"-"`
	XXX_unrecognized            []byte    `json:"-"`
	XXX_sizecache               int32     `json:"-"`
}

func (m *BackfillMatchmakingRequest) Reset()         { *m = BackfillMatchmakingRequest{} }
func (m *BackfillMatchmakingRequest) String() string { return proto.CompactTextString(m) }
func (*BackfillMatchmakingRequest) ProtoMessage()    {}
func (*BackfillMatchmakingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{9}
}

func (m *BackfillMatchmakingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackfillMatchmakingRequest.Unmarshal(m, b)
}
func (m *BackfillMatchmakingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackfillMatchmakingRequest.Marshal(b, m, deterministic)
}
func (m *BackfillMatchmakingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackfillMatchmakingRequest.Merge(m, src)
}
func (m *BackfillMatchmakingRequest) XXX_Size() int {
	return xxx_messageInfo_BackfillMatchmakingRequest.Size(m)
}
func (m *BackfillMatchmakingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackfillMatchmakingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackfillMatchmakingRequest proto.InternalMessageInfo

func (m *BackfillMatchmakingRequest) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *BackfillMatchmakingRequest) GetGameSessionArn() string {
	if m != nil {
		return m.GameSessionArn
	}
	return ""
}

func (m *BackfillMatchmakingRequest) GetMatchmakingConfigurationArn() string {
	if m != nil {
		return m.MatchmakingConfigurationArn
	}
	return ""
}

func (m *BackfillMatchmakingRequest) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type StopMatchmakingRequest struct {
	TicketId                    string   `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	GameSessionArn              string   `protobuf:"bytes,2,opt,name=gameSessionArn,proto3" json:"gameSessionArn,omitempty"`
	MatchmakingConfigurationArn string   `protobuf:"bytes,3,opt,name=matchmakingConfigurationArn,proto3" json:"matchmakingConfigurationArn,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *StopMatchmakingRequest) Reset()         { *m = StopMatchmakingRequest{} }
func (m *StopMatchmakingRequest) String() string { return proto.CompactTextString(m) }
func (*StopMatchmakingRequest) ProtoMessage()    {}
func (*StopMatchmakingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{10}
}

func (m *StopMatchmakingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopMatchmakingRequest.Unmarshal(m, b)
}
func (m *StopMatchmakingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopMatchmakingRequest.Marshal(b, m, deterministic)
}
func (m *StopMatchmakingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopMatchmakingRequest.Merge(m, src)
}
func (m *StopMatchmakingRequest) XXX_Size() int {
	return xxx_messageInfo_StopMatchmakingRequest.Size(m)
}
func (m *StopMatchmakingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopMatchmakingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopMatchmakingRequest proto.InternalMessageInfo

func (m *StopMatchmakingRequest) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *StopMatchmakingRequest) GetGameSessionArn() string {
	if m != nil {
		return m.GameSessionArn
	}
	return ""
}

func (m *StopMatchmakingRequest) GetMatchmakingConfigurationArn() string {
	if m != nil {
		return m.MatchmakingConfigurationArn
	}
	return ""
}

type GetInstanceCertificate struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstanceCertificate) Reset()         { *m = GetInstanceCertificate{} }
func (m *GetInstanceCertificate) String() string { return proto.CompactTextString(m) }
func (*GetInstanceCertificate) ProtoMessage()    {}
func (*GetInstanceCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{11}
}

func (m *GetInstanceCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstanceCertificate.Unmarshal(m, b)
}
func (m *GetInstanceCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstanceCertificate.Marshal(b, m, deterministic)
}
func (m *GetInstanceCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstanceCertificate.Merge(m, src)
}
func (m *GetInstanceCertificate) XXX_Size() int {
	return xxx_messageInfo_GetInstanceCertificate.Size(m)
}
func (m *GetInstanceCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstanceCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstanceCertificate proto.InternalMessageInfo

//AuxProxy --> Sdk
type ActivateGameSession struct {
	GameSession          *GameSession `protobuf:"bytes,1,opt,name=gameSession,proto3" json:"gameSession,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActivateGameSession) Reset()         { *m = ActivateGameSession{} }
func (m *ActivateGameSession) String() string { return proto.CompactTextString(m) }
func (*ActivateGameSession) ProtoMessage()    {}
func (*ActivateGameSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{12}
}

func (m *ActivateGameSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateGameSession.Unmarshal(m, b)
}
func (m *ActivateGameSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateGameSession.Marshal(b, m, deterministic)
}
func (m *ActivateGameSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateGameSession.Merge(m, src)
}
func (m *ActivateGameSession) XXX_Size() int {
	return xxx_messageInfo_ActivateGameSession.Size(m)
}
func (m *ActivateGameSession) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateGameSession.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateGameSession proto.InternalMessageInfo

func (m *ActivateGameSession) GetGameSession() *GameSession {
	if m != nil {
		return m.GameSession
	}
	return nil
}

type TerminateProcess struct {
	TerminationTime      int64    `protobuf:"varint,1,opt,name=terminationTime,proto3" json:"terminationTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminateProcess) Reset()         { *m = TerminateProcess{} }
func (m *TerminateProcess) String() string { return proto.CompactTextString(m) }
func (*TerminateProcess) ProtoMessage()    {}
func (*TerminateProcess) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{13}
}

func (m *TerminateProcess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminateProcess.Unmarshal(m, b)
}
func (m *TerminateProcess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminateProcess.Marshal(b, m, deterministic)
}
func (m *TerminateProcess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminateProcess.Merge(m, src)
}
func (m *TerminateProcess) XXX_Size() int {
	return xxx_messageInfo_TerminateProcess.Size(m)
}
func (m *TerminateProcess) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminateProcess.DiscardUnknown(m)
}

var xxx_messageInfo_TerminateProcess proto.InternalMessageInfo

func (m *TerminateProcess) GetTerminationTime() int64 {
	if m != nil {
		return m.TerminationTime
	}
	return 0
}

type DescribePlayerSessionsResponse struct {
	NextToken            string           `protobuf:"bytes,1,opt,name=nextToken,proto3" json:"nextToken,omitempty"`
	PlayerSessions       []*PlayerSession `protobuf:"bytes,2,rep,name=playerSessions,proto3" json:"playerSessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DescribePlayerSessionsResponse) Reset()         { *m = DescribePlayerSessionsResponse{} }
func (m *DescribePlayerSessionsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribePlayerSessionsResponse) ProtoMessage()    {}
func (*DescribePlayerSessionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{14}
}

func (m *DescribePlayerSessionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePlayerSessionsResponse.Unmarshal(m, b)
}
func (m *DescribePlayerSessionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePlayerSessionsResponse.Marshal(b, m, deterministic)
}
func (m *DescribePlayerSessionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePlayerSessionsResponse.Merge(m, src)
}
func (m *DescribePlayerSessionsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribePlayerSessionsResponse.Size(m)
}
func (m *DescribePlayerSessionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePlayerSessionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePlayerSessionsResponse proto.InternalMessageInfo

func (m *DescribePlayerSessionsResponse) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *DescribePlayerSessionsResponse) GetPlayerSessions() []*PlayerSession {
	if m != nil {
		return m.PlayerSessions
	}
	return nil
}

type UpdateGameSession struct {
	GameSession          *GameSession `protobuf:"bytes,1,opt,name=gameSession,proto3" json:"gameSession,omitempty"`
	UpdateReason         string       `protobuf:"bytes,2,opt,name=updateReason,proto3" json:"updateReason,omitempty"`
	BackfillTicketId     string       `protobuf:"bytes,3,opt,name=backfillTicketId,proto3" json:"backfillTicketId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateGameSession) Reset()         { *m = UpdateGameSession{} }
func (m *UpdateGameSession) String() string { return proto.CompactTextString(m) }
func (*UpdateGameSession) ProtoMessage()    {}
func (*UpdateGameSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{15}
}

func (m *UpdateGameSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGameSession.Unmarshal(m, b)
}
func (m *UpdateGameSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGameSession.Marshal(b, m, deterministic)
}
func (m *UpdateGameSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGameSession.Merge(m, src)
}
func (m *UpdateGameSession) XXX_Size() int {
	return xxx_messageInfo_UpdateGameSession.Size(m)
}
func (m *UpdateGameSession) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGameSession.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGameSession proto.InternalMessageInfo

func (m *UpdateGameSession) GetGameSession() *GameSession {
	if m != nil {
		return m.GameSession
	}
	return nil
}

func (m *UpdateGameSession) GetUpdateReason() string {
	if m != nil {
		return m.UpdateReason
	}
	return ""
}

func (m *UpdateGameSession) GetBackfillTicketId() string {
	if m != nil {
		return m.BackfillTicketId
	}
	return ""
}

type GetInstanceCertificateResponse struct {
	CertificatePath      string   `protobuf:"bytes,1,opt,name=certificatePath,proto3" json:"certificatePath,omitempty"`
	CertificateChainPath string   `protobuf:"bytes,2,opt,name=certificateChainPath,proto3" json:"certificateChainPath,omitempty"`
	PrivateKeyPath       string   `protobuf:"bytes,3,opt,name=privateKeyPath,proto3" json:"privateKeyPath,omitempty"`
	HostName             string   `protobuf:"bytes,4,opt,name=hostName,proto3" json:"hostName,omitempty"`
	RootCertificatePath  string   `protobuf:"bytes,5,opt,name=rootCertificatePath,proto3" json:"rootCertificatePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstanceCertificateResponse) Reset()         { *m = GetInstanceCertificateResponse{} }
func (m *GetInstanceCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*GetInstanceCertificateResponse) ProtoMessage()    {}
func (*GetInstanceCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{16}
}

func (m *GetInstanceCertificateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstanceCertificateResponse.Unmarshal(m, b)
}
func (m *GetInstanceCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstanceCertificateResponse.Marshal(b, m, deterministic)
}
func (m *GetInstanceCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstanceCertificateResponse.Merge(m, src)
}
func (m *GetInstanceCertificateResponse) XXX_Size() int {
	return xxx_messageInfo_GetInstanceCertificateResponse.Size(m)
}
func (m *GetInstanceCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstanceCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstanceCertificateResponse proto.InternalMessageInfo

func (m *GetInstanceCertificateResponse) GetCertificatePath() string {
	if m != nil {
		return m.CertificatePath
	}
	return ""
}

func (m *GetInstanceCertificateResponse) GetCertificateChainPath() string {
	if m != nil {
		return m.CertificateChainPath
	}
	return ""
}

func (m *GetInstanceCertificateResponse) GetPrivateKeyPath() string {
	if m != nil {
		return m.PrivateKeyPath
	}
	return ""
}

func (m *GetInstanceCertificateResponse) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *GetInstanceCertificateResponse) GetRootCertificatePath() string {
	if m != nil {
		return m.RootCertificatePath
	}
	return ""
}

type BackfillMatchmakingResponse struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackfillMatchmakingResponse) Reset()         { *m = BackfillMatchmakingResponse{} }
func (m *BackfillMatchmakingResponse) String() string { return proto.CompactTextString(m) }
func (*BackfillMatchmakingResponse) ProtoMessage()    {}
func (*BackfillMatchmakingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{17}
}

func (m *BackfillMatchmakingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackfillMatchmakingResponse.Unmarshal(m, b)
}
func (m *BackfillMatchmakingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackfillMatchmakingResponse.Marshal(b, m, deterministic)
}
func (m *BackfillMatchmakingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackfillMatchmakingResponse.Merge(m, src)
}
func (m *BackfillMatchmakingResponse) XXX_Size() int {
	return xxx_messageInfo_BackfillMatchmakingResponse.Size(m)
}
func (m *BackfillMatchmakingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackfillMatchmakingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackfillMatchmakingResponse proto.InternalMessageInfo

func (m *BackfillMatchmakingResponse) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

//Common objects
type Response struct {
	Status               Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=com.amazon.whitewater.auxproxy.pbuffer.Response_Status" json:"status,omitempty"`
	ErrorMessage         string          `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{18}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_OK
}

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GameLiftResponse struct {
	Status               GameLiftResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=com.amazon.whitewater.auxproxy.pbuffer.GameLiftResponse_Status" json:"status,omitempty"`
	ResponseData         string                  `protobuf:"bytes,2,opt,name=responseData,proto3" json:"responseData,omitempty"`
	ErrorMessage         string                  `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GameLiftResponse) Reset()         { *m = GameLiftResponse{} }
func (m *GameLiftResponse) String() string { return proto.CompactTextString(m) }
func (*GameLiftResponse) ProtoMessage()    {}
func (*GameLiftResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{19}
}

func (m *GameLiftResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameLiftResponse.Unmarshal(m, b)
}
func (m *GameLiftResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameLiftResponse.Marshal(b, m, deterministic)
}
func (m *GameLiftResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameLiftResponse.Merge(m, src)
}
func (m *GameLiftResponse) XXX_Size() int {
	return xxx_messageInfo_GameLiftResponse.Size(m)
}
func (m *GameLiftResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameLiftResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameLiftResponse proto.InternalMessageInfo

func (m *GameLiftResponse) GetStatus() GameLiftResponse_Status {
	if m != nil {
		return m.Status
	}
	return GameLiftResponse_OK
}

func (m *GameLiftResponse) GetResponseData() string {
	if m != nil {
		return m.ResponseData
	}
	return ""
}

func (m *GameLiftResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GameSession struct {
	GameSessionId        string          `protobuf:"bytes,1,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	FleetId              string          `protobuf:"bytes,2,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MaxPlayers           int32           `protobuf:"varint,4,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	Joinable             bool            `protobuf:"varint,5,opt,name=joinable,proto3" json:"joinable,omitempty"`
	GameProperties       []*GameProperty `protobuf:"bytes,6,rep,name=gameProperties,proto3" json:"gameProperties,omitempty"`
	IpAddress            string          `protobuf:"bytes,7,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Port                 int32           `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	GameSessionData      string          `protobuf:"bytes,9,opt,name=gameSessionData,proto3" json:"gameSessionData,omitempty"`
	MatchmakerData       string          `protobuf:"bytes,10,opt,name=matchmakerData,proto3" json:"matchmakerData,omitempty"`
	DnsName              string          `protobuf:"bytes,11,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameSession) Reset()         { *m = GameSession{} }
func (m *GameSession) String() string { return proto.CompactTextString(m) }
func (*GameSession) ProtoMessage()    {}
func (*GameSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{20}
}

func (m *GameSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSession.Unmarshal(m, b)
}
func (m *GameSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSession.Marshal(b, m, deterministic)
}
func (m *GameSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSession.Merge(m, src)
}
func (m *GameSession) XXX_Size() int {
	return xxx_messageInfo_GameSession.Size(m)
}
func (m *GameSession) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSession.DiscardUnknown(m)
}

var xxx_messageInfo_GameSession proto.InternalMessageInfo

func (m *GameSession) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

func (m *GameSession) GetFleetId() string {
	if m != nil {
		return m.FleetId
	}
	return ""
}

func (m *GameSession) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameSession) GetMaxPlayers() int32 {
	if m != nil {
		return m.MaxPlayers
	}
	return 0
}

func (m *GameSession) GetJoinable() bool {
	if m != nil {
		return m.Joinable
	}
	return false
}

func (m *GameSession) GetGameProperties() []*GameProperty {
	if m != nil {
		return m.GameProperties
	}
	return nil
}

func (m *GameSession) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *GameSession) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GameSession) GetGameSessionData() string {
	if m != nil {
		return m.GameSessionData
	}
	return ""
}

func (m *GameSession) GetMatchmakerData() string {
	if m != nil {
		return m.MatchmakerData
	}
	return ""
}

func (m *GameSession) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

type GameProperty struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameProperty) Reset()         { *m = GameProperty{} }
func (m *GameProperty) String() string { return proto.CompactTextString(m) }
func (*GameProperty) ProtoMessage()    {}
func (*GameProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{21}
}

func (m *GameProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameProperty.Unmarshal(m, b)
}
func (m *GameProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameProperty.Marshal(b, m, deterministic)
}
func (m *GameProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameProperty.Merge(m, src)
}
func (m *GameProperty) XXX_Size() int {
	return xxx_messageInfo_GameProperty.Size(m)
}
func (m *GameProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_GameProperty.DiscardUnknown(m)
}

var xxx_messageInfo_GameProperty proto.InternalMessageInfo

func (m *GameProperty) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GameProperty) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PlayerSession struct {
	PlayerSessionId      string   `protobuf:"bytes,1,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	GameSessionId        string   `protobuf:"bytes,3,opt,name=gameSessionId,proto3" json:"gameSessionId,omitempty"`
	FleetId              string   `protobuf:"bytes,4,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	IpAddress            string   `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreationTime         int64    `protobuf:"varint,7,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	TerminationTime      int64    `protobuf:"varint,8,opt,name=terminationTime,proto3" json:"terminationTime,omitempty"`
	Port                 int32    `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`
	PlayerData           string   `protobuf:"bytes,10,opt,name=playerData,proto3" json:"playerData,omitempty"`
	DnsName              string   `protobuf:"bytes,11,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSession) Reset()         { *m = PlayerSession{} }
func (m *PlayerSession) String() string { return proto.CompactTextString(m) }
func (*PlayerSession) ProtoMessage()    {}
func (*PlayerSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{22}
}

func (m *PlayerSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSession.Unmarshal(m, b)
}
func (m *PlayerSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSession.Marshal(b, m, deterministic)
}
func (m *PlayerSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSession.Merge(m, src)
}
func (m *PlayerSession) XXX_Size() int {
	return xxx_messageInfo_PlayerSession.Size(m)
}
func (m *PlayerSession) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSession.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSession proto.InternalMessageInfo

func (m *PlayerSession) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

func (m *PlayerSession) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerSession) GetGameSessionId() string {
	if m != nil {
		return m.GameSessionId
	}
	return ""
}

func (m *PlayerSession) GetFleetId() string {
	if m != nil {
		return m.FleetId
	}
	return ""
}

func (m *PlayerSession) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *PlayerSession) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlayerSession) GetCreationTime() int64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *PlayerSession) GetTerminationTime() int64 {
	if m != nil {
		return m.TerminationTime
	}
	return 0
}

func (m *PlayerSession) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PlayerSession) GetPlayerData() string {
	if m != nil {
		return m.PlayerData
	}
	return ""
}

func (m *PlayerSession) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

type Player struct {
	PlayerId             string                     `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerAttributes     map[string]*AttributeValue `protobuf:"bytes,2,rep,name=playerAttributes,proto3" json:"playerAttributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Team                 string                     `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	LatencyInMs          map[string]int32           `protobuf:"bytes,4,rep,name=latencyInMs,proto3" json:"latencyInMs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{23}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *Player) GetPlayerAttributes() map[string]*AttributeValue {
	if m != nil {
		return m.PlayerAttributes
	}
	return nil
}

func (m *Player) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Player) GetLatencyInMs() map[string]int32 {
	if m != nil {
		return m.LatencyInMs
	}
	return nil
}

type AttributeValue struct {
	Type                 int32              `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	S                    string             `protobuf:"bytes,2,opt,name=S,proto3" json:"S,omitempty"`
	N                    float64            `protobuf:"fixed64,3,opt,name=N,proto3" json:"N,omitempty"`
	SL                   []string           `protobuf:"bytes,4,rep,name=SL,proto3" json:"SL,omitempty"`
	SDM                  map[string]float64 `protobuf:"bytes,5,rep,name=SDM,proto3" json:"SDM,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AttributeValue) Reset()         { *m = AttributeValue{} }
func (m *AttributeValue) String() string { return proto.CompactTextString(m) }
func (*AttributeValue) ProtoMessage()    {}
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{24}
}

func (m *AttributeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeValue.Unmarshal(m, b)
}
func (m *AttributeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeValue.Marshal(b, m, deterministic)
}
func (m *AttributeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeValue.Merge(m, src)
}
func (m *AttributeValue) XXX_Size() int {
	return xxx_messageInfo_AttributeValue.Size(m)
}
func (m *AttributeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeValue.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeValue proto.InternalMessageInfo

func (m *AttributeValue) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AttributeValue) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *AttributeValue) GetN() float64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *AttributeValue) GetSL() []string {
	if m != nil {
		return m.SL
	}
	return nil
}

func (m *AttributeValue) GetSDM() map[string]float64 {
	if m != nil {
		return m.SDM
	}
	return nil
}

func init() {
	proto.RegisterEnum("com.amazon.whitewater.auxproxy.pbuffer.Response_Status", Response_Status_name, Response_Status_value)
	proto.RegisterEnum("com.amazon.whitewater.auxproxy.pbuffer.GameLiftResponse_Status", GameLiftResponse_Status_name, GameLiftResponse_Status_value)
	proto.RegisterType((*ProcessReady)(nil), "com.amazon.whitewater.auxproxy.pbuffer.ProcessReady")
	proto.RegisterType((*ProcessEnding)(nil), "com.amazon.whitewater.auxproxy.pbuffer.ProcessEnding")
	proto.RegisterType((*GameSessionActivate)(nil), "com.amazon.whitewater.auxproxy.pbuffer.GameSessionActivate")
	proto.RegisterType((*GameSessionTerminate)(nil), "com.amazon.whitewater.auxproxy.pbuffer.GameSessionTerminate")
	proto.RegisterType((*UpdatePlayerSessionCreationPolicy)(nil), "com.amazon.whitewater.auxproxy.pbuffer.UpdatePlayerSessionCreationPolicy")
	proto.RegisterType((*AcceptPlayerSession)(nil), "com.amazon.whitewater.auxproxy.pbuffer.AcceptPlayerSession")
	proto.RegisterType((*RemovePlayerSession)(nil), "com.amazon.whitewater.auxproxy.pbuffer.RemovePlayerSession")
	proto.RegisterType((*ReportHealth)(nil), "com.amazon.whitewater.auxproxy.pbuffer.ReportHealth")
	proto.RegisterType((*DescribePlayerSessionsRequest)(nil), "com.amazon.whitewater.auxproxy.pbuffer.DescribePlayerSessionsRequest")
	proto.RegisterType((*BackfillMatchmakingRequest)(nil), "com.amazon.whitewater.auxproxy.pbuffer.BackfillMatchmakingRequest")
	proto.RegisterType((*StopMatchmakingRequest)(nil), "com.amazon.whitewater.auxproxy.pbuffer.StopMatchmakingRequest")
	proto.RegisterType((*GetInstanceCertificate)(nil), "com.amazon.whitewater.auxproxy.pbuffer.GetInstanceCertificate")
	proto.RegisterType((*ActivateGameSession)(nil), "com.amazon.whitewater.auxproxy.pbuffer.ActivateGameSession")
	proto.RegisterType((*TerminateProcess)(nil), "com.amazon.whitewater.auxproxy.pbuffer.TerminateProcess")
	proto.RegisterType((*DescribePlayerSessionsResponse)(nil), "com.amazon.whitewater.auxproxy.pbuffer.DescribePlayerSessionsResponse")
	proto.RegisterType((*UpdateGameSession)(nil), "com.amazon.whitewater.auxproxy.pbuffer.UpdateGameSession")
	proto.RegisterType((*GetInstanceCertificateResponse)(nil), "com.amazon.whitewater.auxproxy.pbuffer.GetInstanceCertificateResponse")
	proto.RegisterType((*BackfillMatchmakingResponse)(nil), "com.amazon.whitewater.auxproxy.pbuffer.BackfillMatchmakingResponse")
	proto.RegisterType((*Response)(nil), "com.amazon.whitewater.auxproxy.pbuffer.Response")
	proto.RegisterType((*GameLiftResponse)(nil), "com.amazon.whitewater.auxproxy.pbuffer.GameLiftResponse")
	proto.RegisterType((*GameSession)(nil), "com.amazon.whitewater.auxproxy.pbuffer.GameSession")
	proto.RegisterType((*GameProperty)(nil), "com.amazon.whitewater.auxproxy.pbuffer.GameProperty")
	proto.RegisterType((*PlayerSession)(nil), "com.amazon.whitewater.auxproxy.pbuffer.PlayerSession")
	proto.RegisterType((*Player)(nil), "com.amazon.whitewater.auxproxy.pbuffer.Player")
	proto.RegisterMapType((map[string]int32)(nil), "com.amazon.whitewater.auxproxy.pbuffer.Player.LatencyInMsEntry")
	proto.RegisterMapType((map[string]*AttributeValue)(nil), "com.amazon.whitewater.auxproxy.pbuffer.Player.PlayerAttributesEntry")
	proto.RegisterType((*AttributeValue)(nil), "com.amazon.whitewater.auxproxy.pbuffer.AttributeValue")
	proto.RegisterMapType((map[string]float64)(nil), "com.amazon.whitewater.auxproxy.pbuffer.AttributeValue.SDMEntry")
}

func init() { proto.RegisterFile("sdk.proto", fileDescriptor_70decb0fb6f436df) }

var fileDescriptor_70decb0fb6f436df = []byte{
	// 1323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4d, 0x6f, 0x1b, 0xc5,
	0x1b, 0xff, 0x8f, 0x1d, 0x3b, 0xf6, 0xe3, 0xbc, 0xb8, 0x9b, 0xfe, 0x2b, 0xe3, 0x42, 0x54, 0x56,
	0xa8, 0xb2, 0x38, 0xb8, 0x51, 0xfa, 0xc2, 0x8b, 0x2a, 0x4a, 0x9a, 0xf4, 0x25, 0x6a, 0xd2, 0x86,
	0x75, 0x0a, 0x12, 0x02, 0xa1, 0xc9, 0x7a, 0x6c, 0x2f, 0xde, 0xdd, 0x59, 0x66, 0xc6, 0x6d, 0x0c,
	0x5f, 0x81, 0x0b, 0x47, 0x24, 0xe0, 0x83, 0xf0, 0x11, 0xf8, 0x0a, 0x1c, 0x39, 0x70, 0xe1, 0xc8,
	0x15, 0x09, 0xcd, 0xcc, 0xee, 0x7a, 0x76, 0xbd, 0x4d, 0x9c, 0x43, 0x25, 0x4e, 0x9e, 0xf9, 0xed,
	0x33, 0xcf, 0xfc, 0x9e, 0xd7, 0x79, 0x64, 0xa8, 0xf3, 0xfe, 0xb8, 0x1b, 0x31, 0x2a, 0xa8, 0x75,
	0xdd, 0xa5, 0x41, 0x17, 0x07, 0xf8, 0x5b, 0x1a, 0x76, 0x5f, 0x8e, 0x3c, 0x41, 0x5e, 0x62, 0x41,
	0x58, 0x17, 0x4f, 0x4e, 0x23, 0x46, 0x4f, 0xa7, 0xdd, 0xe8, 0x64, 0x32, 0x18, 0x10, 0x66, 0x7f,
	0x8f, 0x60, 0xe5, 0x88, 0x51, 0x97, 0x70, 0xee, 0x10, 0xdc, 0x9f, 0x5a, 0xef, 0x42, 0xd3, 0xa7,
	0xc3, 0x23, 0x2c, 0x46, 0xfc, 0x98, 0x3e, 0x8f, 0x7c, 0x8a, 0xfb, 0x2d, 0x74, 0xad, 0xdc, 0xa9,
	0x3b, 0x73, 0xb8, 0x65, 0xc1, 0x52, 0x44, 0x99, 0x68, 0x95, 0xae, 0xa1, 0x4e, 0xc5, 0x51, 0x6b,
	0xeb, 0x2e, 0xbc, 0x11, 0xe0, 0xd3, 0x5d, 0x1a, 0xba, 0x13, 0xc6, 0x48, 0x28, 0x1e, 0xe1, 0x80,
	0xf4, 0x08, 0xe7, 0x1e, 0x0d, 0x79, 0xab, 0xac, 0x04, 0x5f, 0x2d, 0x60, 0xaf, 0xc3, 0x6a, 0xcc,
	0xe6, 0x41, 0xd8, 0xf7, 0xc2, 0xa1, 0x4d, 0x61, 0xc3, 0x10, 0xd8, 0x71, 0x85, 0xf7, 0x02, 0x0b,
	0x62, 0xbd, 0x03, 0xab, 0xc3, 0x19, 0xbc, 0x2f, 0x29, 0xa2, 0x4e, 0xdd, 0xc9, 0x82, 0xd6, 0x26,
	0x40, 0x80, 0x4f, 0x8f, 0x7c, 0x3c, 0x25, 0x8c, 0xc7, 0x2c, 0x0d, 0x24, 0xe5, 0x5f, 0x9e, 0xf1,
	0xb7, 0xef, 0xc2, 0x65, 0xe3, 0xc2, 0x63, 0xc2, 0x02, 0x2f, 0x5c, 0xf8, 0x46, 0xfb, 0x07, 0x04,
	0x6f, 0x3f, 0x8f, 0xfa, 0x58, 0x10, 0x7d, 0x47, 0xfc, 0x65, 0x97, 0x11, 0x2c, 0x3c, 0x1a, 0x1e,
	0x51, 0xdf, 0x73, 0xa7, 0x0b, 0xb2, 0x7f, 0x08, 0x9b, 0x21, 0x79, 0x79, 0x86, 0x1e, 0x65, 0x51,
	0xdd, 0x39, 0x47, 0xca, 0x26, 0xb0, 0xb1, 0xe3, 0xba, 0x24, 0x12, 0x19, 0xa1, 0x05, 0x49, 0x74,
	0x60, 0x3d, 0x32, 0x8f, 0xed, 0xf7, 0xe3, 0x5b, 0xf3, 0xb0, 0xbc, 0xc6, 0x21, 0x01, 0x7d, 0x41,
	0x5e, 0xef, 0x35, 0xdb, 0xb0, 0xe2, 0x10, 0x19, 0xa9, 0xc7, 0x04, 0xfb, 0x62, 0x64, 0xd9, 0xb0,
	0x32, 0x52, 0xab, 0x9e, 0xc0, 0x62, 0xc2, 0x95, 0xfa, 0x9a, 0x93, 0xc1, 0xec, 0x7f, 0x10, 0xbc,
	0xb5, 0x47, 0xb8, 0xcb, 0xbc, 0x93, 0x2c, 0x3b, 0xee, 0x90, 0x6f, 0x26, 0x84, 0x8b, 0x05, 0x59,
	0xb6, 0xa1, 0xa6, 0xe9, 0xa4, 0xf4, 0xd2, 0x7d, 0x91, 0x05, 0xe5, 0x42, 0x0b, 0x64, 0x85, 0x64,
	0x20, 0x4d, 0xf2, 0xa1, 0xe7, 0x0b, 0xc2, 0x5a, 0x4b, 0xea, 0xcc, 0xab, 0x05, 0xac, 0x37, 0xa1,
	0x1e, 0x92, 0x53, 0x71, 0x4c, 0xc7, 0x24, 0x6c, 0x55, 0x94, 0xf4, 0x0c, 0xb0, 0x2e, 0x43, 0xc5,
	0xf7, 0x02, 0x4f, 0xb4, 0xaa, 0x2a, 0xa5, 0xf5, 0xc6, 0xfe, 0x0b, 0x41, 0xfb, 0x3e, 0x76, 0xc7,
	0x03, 0xcf, 0xf7, 0x0f, 0xb1, 0x70, 0x47, 0x01, 0x1e, 0x7b, 0xe1, 0x30, 0x31, 0xbe, 0x0d, 0x35,
	0xe1, 0xb9, 0x63, 0x22, 0x52, 0xbb, 0xd3, 0xbd, 0x75, 0x1d, 0xd6, 0x0c, 0x1f, 0xec, 0xb0, 0x30,
	0x36, 0x3c, 0x87, 0x5a, 0x1f, 0xc3, 0xd5, 0x60, 0xa6, 0x79, 0x97, 0x86, 0x03, 0x6f, 0x38, 0x61,
	0x2a, 0x0d, 0xe5, 0x21, 0xed, 0x8a, 0xb3, 0x44, 0xac, 0xc7, 0xb0, 0x1c, 0xc5, 0x95, 0xba, 0x74,
	0xad, 0xdc, 0x69, 0x6c, 0x77, 0xbb, 0x8b, 0xf5, 0xb0, 0xae, 0x0e, 0xa9, 0x93, 0x1c, 0xb7, 0x7f,
	0x41, 0x70, 0xa5, 0x27, 0x68, 0xf4, 0x5f, 0x35, 0xd5, 0x6e, 0xc1, 0x95, 0x47, 0x44, 0xec, 0x87,
	0x5c, 0xe0, 0xd0, 0x25, 0xbb, 0x84, 0x09, 0x6f, 0xe0, 0xb9, 0x58, 0x10, 0xdb, 0x97, 0xb5, 0xaa,
	0x7b, 0x9c, 0xd1, 0x85, 0xac, 0xe7, 0xd0, 0x30, 0x48, 0x28, 0xe6, 0x8d, 0xed, 0x9b, 0x8b, 0xfa,
	0xc7, 0xd0, 0xe4, 0x98, 0x7a, 0xec, 0xbb, 0xd0, 0x4c, 0x1b, 0x5c, 0xdc, 0x76, 0x65, 0x1e, 0x8b,
	0x18, 0x93, 0xfd, 0xcf, 0x0b, 0x88, 0xba, 0xae, 0xec, 0xe4, 0x61, 0xfb, 0x67, 0x04, 0x9b, 0xaf,
	0xaa, 0x2a, 0x1e, 0xd1, 0x90, 0x93, 0x6c, 0xb2, 0xa2, 0x7c, 0xb2, 0x7e, 0x09, 0x6b, 0x99, 0x3c,
	0x97, 0x2d, 0x5a, 0x06, 0xfe, 0xf6, 0xc5, 0x02, 0x9f, 0x98, 0x96, 0x53, 0x66, 0xff, 0x8a, 0xe0,
	0x92, 0xee, 0xc5, 0xaf, 0xdf, 0x95, 0xb2, 0x0d, 0x4d, 0xd4, 0x5d, 0x0e, 0xc1, 0x9c, 0x26, 0xa9,
	0x93, 0xc1, 0xe4, 0xd3, 0x7a, 0x12, 0x57, 0xe1, 0x71, 0x92, 0x84, 0x3a, 0x5b, 0xe6, 0x70, 0xfb,
	0x6f, 0x04, 0x9b, 0xc5, 0x39, 0x92, 0x3a, 0xb7, 0x03, 0xeb, 0xee, 0x0c, 0x96, 0x2f, 0x73, 0xec,
	0xe2, 0x3c, 0x6c, 0x6d, 0xc3, 0x65, 0x03, 0xda, 0x1d, 0x61, 0x2f, 0x54, 0xe2, 0x9a, 0x64, 0xe1,
	0x37, 0x59, 0x0d, 0x11, 0x53, 0x89, 0xf8, 0x84, 0x4c, 0x95, 0xb4, 0xa6, 0x9a, 0x43, 0x65, 0x45,
	0x8d, 0x28, 0x17, 0x4f, 0x71, 0x40, 0xe2, 0xe6, 0x95, 0xee, 0xad, 0x2d, 0xd8, 0x60, 0x94, 0x8a,
	0xdd, 0x1c, 0x4b, 0xdd, 0xb5, 0x8a, 0x3e, 0xd9, 0x1f, 0xc0, 0xd5, 0xc2, 0x46, 0x15, 0x9b, 0x7c,
	0x46, 0xf9, 0xda, 0x3f, 0x21, 0xa8, 0xa5, 0x82, 0xcf, 0xa0, 0xca, 0x67, 0xef, 0xc1, 0xda, 0xf6,
	0x7b, 0x8b, 0x06, 0x38, 0xd1, 0xd0, 0xd5, 0x4d, 0xd7, 0x89, 0xd5, 0xc8, 0xf8, 0x12, 0xc6, 0x28,
	0x3b, 0x24, 0x9c, 0xe3, 0x21, 0x49, 0xe2, 0x6b, 0x62, 0xf6, 0x55, 0xa8, 0xea, 0x53, 0x56, 0x15,
	0x4a, 0xcf, 0x9e, 0x34, 0xff, 0x67, 0xd5, 0xa1, 0xf2, 0xc0, 0x71, 0x9e, 0x39, 0x4d, 0x64, 0xff,
	0x81, 0xa0, 0x29, 0xb3, 0xe7, 0xc0, 0x1b, 0x88, 0x94, 0xe6, 0x67, 0x39, 0x9a, 0xf7, 0x2e, 0x92,
	0x87, 0xa6, 0xa6, 0x02, 0xba, 0x2c, 0xfe, 0xb4, 0x87, 0x05, 0x4e, 0xe8, 0x9a, 0xd8, 0x9c, 0x49,
	0xe5, 0x02, 0x93, 0xba, 0x73, 0x26, 0xad, 0x42, 0x5d, 0x99, 0xf4, 0xd5, 0xad, 0xad, 0xad, 0x26,
	0x9a, 0x6d, 0x6f, 0x6f, 0x6d, 0x35, 0x4b, 0xf6, 0x8f, 0x65, 0x68, 0x98, 0xd5, 0xb6, 0xd8, 0xbb,
	0xda, 0x82, 0xe5, 0x81, 0x4f, 0x54, 0x54, 0x35, 0xd1, 0x64, 0x2b, 0x27, 0xb4, 0x50, 0x66, 0x96,
	0xe6, 0xa6, 0xd6, 0xb9, 0xa9, 0x6e, 0x69, 0x6e, 0xaa, 0x6b, 0x43, 0xed, 0x6b, 0xea, 0x85, 0xf8,
	0xc4, 0x27, 0x2a, 0xd5, 0x6a, 0x4e, 0xba, 0xb7, 0xbe, 0xd0, 0x3d, 0xfe, 0x88, 0xd1, 0x48, 0x66,
	0x1e, 0xe1, 0xad, 0xaa, 0x6a, 0x39, 0xb7, 0x2e, 0xe2, 0xf8, 0xf8, 0xf4, 0xd4, 0xc9, 0xe9, 0x92,
	0xed, 0xce, 0x8b, 0x76, 0xfa, 0x7d, 0x46, 0x38, 0x6f, 0x2d, 0xeb, 0x76, 0x97, 0x02, 0xe9, 0xb4,
	0x59, 0x33, 0xa6, 0xe5, 0x0e, 0xac, 0x1b, 0xae, 0x50, 0xa1, 0xaa, 0xeb, 0x1a, 0xce, 0xc1, 0xb2,
	0x1e, 0x93, 0x27, 0x85, 0x30, 0x25, 0x08, 0xba, 0x1e, 0xb3, 0xa8, 0xf4, 0x65, 0x3f, 0xe4, 0xaa,
	0x1c, 0x1b, 0xda, 0x97, 0xf1, 0xd6, 0xbe, 0x03, 0x2b, 0x26, 0x7b, 0xab, 0x09, 0xe5, 0x31, 0x99,
	0xc6, 0x11, 0x91, 0x4b, 0x39, 0x3d, 0xbc, 0xc0, 0xfe, 0x24, 0xc9, 0x6e, 0xbd, 0xb1, 0xff, 0x2c,
	0xc1, 0x6a, 0x76, 0xa6, 0x2b, 0x98, 0x75, 0x50, 0xf1, 0xac, 0x73, 0xd6, 0xc4, 0x34, 0x97, 0x1b,
	0xe5, 0x73, 0x72, 0x63, 0x29, 0x9b, 0x1b, 0x19, 0x6f, 0x57, 0xf2, 0xde, 0xbe, 0x92, 0x96, 0x56,
	0x55, 0x7d, 0x32, 0x2a, 0xc3, 0x8d, 0xe7, 0x63, 0xf5, 0xb8, 0x2d, 0xab, 0xc7, 0x2d, 0x83, 0x15,
	0xbd, 0x81, 0xb5, 0xc2, 0x37, 0x30, 0x8d, 0x69, 0xdd, 0x88, 0xe9, 0x26, 0x80, 0xb6, 0xd1, 0x88,
	0x92, 0x81, 0x9c, 0x11, 0xa1, 0xdf, 0xca, 0x50, 0xd5, 0x9e, 0xce, 0x38, 0x0e, 0xe5, 0x1c, 0x17,
	0x41, 0x53, 0xaf, 0x77, 0x84, 0x60, 0xde, 0xc9, 0x44, 0x90, 0xe4, 0xe5, 0xdc, 0xbb, 0xd8, 0xcb,
	0x19, 0xff, 0xcc, 0xd4, 0x3c, 0x08, 0x05, 0x9b, 0x3a, 0x73, 0xda, 0xa5, 0x99, 0x82, 0xe0, 0x20,
	0x29, 0x43, 0xb9, 0xb6, 0x30, 0x34, 0x7c, 0x2c, 0x48, 0xe8, 0x4e, 0xf7, 0xc3, 0xc3, 0x64, 0x66,
	0xbb, 0x77, 0x41, 0x02, 0x07, 0x33, 0x0d, 0xfa, 0x6e, 0x53, 0x67, 0xfb, 0x3b, 0xf8, 0x7f, 0x21,
	0xc3, 0x82, 0xd4, 0x3d, 0x30, 0x53, 0xb7, 0xb1, 0x7d, 0x67, 0x51, 0x1e, 0xa9, 0xe6, 0x4f, 0xe5,
	0xe9, 0x38, 0xe5, 0x3f, 0x2c, 0xbd, 0x8f, 0xda, 0x1f, 0x41, 0x33, 0xcf, 0xee, 0xbc, 0x92, 0xa9,
	0x18, 0xe7, 0xed, 0xdf, 0x11, 0xac, 0x65, 0xb5, 0x2b, 0x37, 0x4e, 0x23, 0x3d, 0x50, 0x55, 0x1c,
	0xb5, 0xb6, 0x56, 0x00, 0xf5, 0xe2, 0xd2, 0x40, 0x3d, 0xb9, 0x7b, 0xaa, 0xbc, 0x8c, 0x1c, 0xf4,
	0xd4, 0x5a, 0x83, 0x52, 0xef, 0x40, 0x79, 0xb6, 0xee, 0x94, 0x7a, 0x07, 0xd6, 0x27, 0x50, 0xee,
	0xed, 0x1d, 0xb6, 0x2a, 0x17, 0x73, 0x75, 0x96, 0x44, 0xb7, 0xb7, 0x77, 0xa8, 0x5d, 0x2d, 0x75,
	0xb5, 0xef, 0x40, 0x2d, 0x01, 0xce, 0xb3, 0x0e, 0x19, 0xd6, 0xdd, 0xdf, 0xf8, 0xfc, 0x52, 0x34,
	0x1e, 0xde, 0x50, 0x7f, 0x36, 0xdc, 0x88, 0x6f, 0x3a, 0xa9, 0xaa, 0xed, 0xcd, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xd3, 0x89, 0x6d, 0x63, 0x88, 0x10, 0x00, 0x00,
}
